name: CodeQL Analysis

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  analyze:
    runs-on: ubuntu-latest

    permissions:
      security-events: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript-typescript

      - name: Build Angular app
        run: npm run build

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3